config/routes.rb
Affiliate::Application.routes.draw do
  resources :campaigns

  get "home/index"
  get '/:affiliate' => 'home#index'
  root :to => 'home#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :desc, :email, :fname, :img, :lat, :lname, :lng, :location, :source, :title, :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @params = set_params_for_affiliate(params[:affiliate])
  end

 private

  def set_params_for_affiliate(affiliate)
    case affiliate
      when 'affiliate1'
        {
          source: 'http://www.ccfoa.org',
          title: 'Their hope for tomorrow DEPEND on help today',
          location: '2317 West Emory Road, Powell, TN 37849',
          lat: '36.027575',
          lng: '-84.033896',
          desc: 'We are raising funds for HireInfluence. Please help reach our goal of $1,500,000!',
          img: 'http://www.ccfoa.org/images/slider-img1.jpg',
          email: 'jason@hireinfluence.com'
        }
      when 'affiliate2'
        {
            source: 'http://www.unicef.org/',
            title: 'Innovation for every child',
            location: '44th Street between 1st and 2nd Avenues New York, New York',
            lat: '40.712784',
            lng: '-74.005941',
            desc: 'We are raising funds for HireInfluence. Please help reach our goal of $1,500,000!',
            img: 'http://unicef-sowc-2015.s3.amazonaws.com/wp-content/uploads/2014/10/13205728/h1.png',
            email: 'jason@hireinfluence.com'
        }

      when 'affiliate3'
        {
            source: 'https://www.childfund.org/',
            title: 'GIVE HOPE TO A CHILD IN NEED',
            location: '2821 Emerywood Parkway, Richmond, VA 23294',
            lat: '37.607980',
            lng: '-77.525527',
            desc: 'We are raising funds for HireInfluence. Please help reach our goal of $1,500,000!',
            img: 'https://www.childfund.org/uploadedImages/public_site/homepage/Hero_Rotator/BIA-sponsorship-EOY3.jpg',
            email: 'jason@hireinfluence.com'
        }

      else
        {
          source: 'http://www.centered.com',
          title: 'We are raising funds for HireInfluence',
          location: 'New York, NY, United States',
          lat: '40.7127837',
          lng: '-74.0059413',
          desc: 'We are raising funds for "Centered" our Yoga and Fitness App.',
          img: 'http://serene-everglades-3138.herokuapp.com/assets/HiRes.jpg',
          email: 'jason@hireinfluence.com'
        }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/campaigns/_form.html.haml
= form_for @campaign do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :source
    = f.text_field :source
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lng
    = f.text_field :lng
  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.label :img
    = f.text_field :img
  .field
    = f.label :token
    = f.text_field :token
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :fname
    = f.text_field :fname
  .field
    = f.label :lname
    = f.text_field :lname
  .actions
    = f.submit 'Save'

app/views/campaigns/edit.html.haml
%h1 Editing campaign

= render 'form'

= link_to 'Show', @campaign
\|
= link_to 'Back', campaigns_path

app/views/campaigns/index.html.haml
%h1 Listing campaigns

%table
  %tr
    %th Source
    %th Title
    %th Location
    %th Lat
    %th Lng
    %th Desc
    %th Img
    %th Token
    %th Email
    %th Fname
    %th Lname
    %th
    %th
    %th

  - @campaigns.each do |campaign|
    %tr
      %td= campaign.source
      %td= campaign.title
      %td= campaign.location
      %td= campaign.lat
      %td= campaign.lng
      %td= campaign.desc
      %td= campaign.img
      %td= campaign.token
      %td= campaign.email
      %td= campaign.fname
      %td= campaign.lname
      %td= link_to 'Show', campaign
      %td= link_to 'Edit', edit_campaign_path(campaign)
      %td= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Campaign', new_campaign_path

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/show.html.haml
%p#notice= notice

%p
  %b Source:
  = @campaign.source
%p
  %b Title:
  = @campaign.title
%p
  %b Location:
  = @campaign.location
%p
  %b Lat:
  = @campaign.lat
%p
  %b Lng:
  = @campaign.lng
%p
  %b Desc:
  = @campaign.desc
%p
  %b Img:
  = @campaign.img
%p
  %b Token:
  = @campaign.token
%p
  %b Email:
  = @campaign.email
%p
  %b Fname:
  = @campaign.fname
%p
  %b Lname:
  = @campaign.lname

= link_to 'Edit', edit_campaign_path(@campaign)
\|
= link_to 'Back', campaigns_path

app/views/home/index.html.haml
.container
  .promoteButtonBox#item
  .bigImgBox
    = image_tag 'HiRes.jpg', height: '445', width: '593'

:javascript
  var params = { auth_mode: 'in', source: '#{@params[:source]}',
  title: '#{@params[:title]}',
  location: '#{@params[:location]}',
  lat: '#{@params[:lat]}',
  lng: '#{@params[:lng]}',
  desc: '#{@params[:desc]}',
  img: '#{@params[:img]}',
  token: '99124566b0a9ef8ab914567d98824919',
  email: '#{@params[:email]}',
   fname: 'Jason',
   lname: 'Pampell',
   }
  var p1 = new AdvoWireAffiliate('item', params);

  $(function(){
  	$('input[type=text], textarea').on('blur', function(){
  		var field = $(this).attr('name');
  		params[field] = $(this).val();
  		console.log($(this).attr('name') + ' -- '+$(this).val());
  		$('#item').html('');
  		p1 = new AdvoWireAffiliate('item', params);
  	});
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Affiliate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'https://stagez.advowire.com/javascripts/advowire_affiliate.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>